title: Kinyanjui Wangonya
description: > # this means to ignore newlines until "baseurl:"
  Kinyanjui Wangonya is a javascript coder, web, and mobile app developer focusing on front-end development. He reads widely, is open minded,
  and is always hungry to keep learning more. He runs a simple blog on his website. Find out more about him here.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wangonya.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kinyanjui Wangonya # add your name
author-img: me.jpg # add your photo
about-author: ğŸ‘¨ğŸ¾â€ğŸ’» # add description
social-twitter: wang0nya
social-github: wangonya # add your Github handle
social-linkedin: wangonya # add your Linkedin handle
social-email: kwangonya@gmail.com # add your Email address

# Disqus
# discus-identifier: wang0nya # add your discus identifier

# Tracker
analytics: UA-122307986-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
